version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc_nvidia_app
    volumes:
      - ./:/app/
    command: /bin/bash -c "./build/gRPCNvidia"
    restart: always

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc_nvidia_python
    volumes:
      - ./:/app/
    command: /bin/bash -c "cd Python && source env/bin/activate && python3 Client.py"
    restart: always
  
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc_nvidia_test
    volumes:
      - ./:/app/ 
    command: /bin/bash -c "cd tests && ctest"
