version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc_nvidia_app
    command: /bin/bash -c "./build/gRPCNvidia"
    volumes:
      - ./:/app/
    restart: always
