version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: grpc_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "50051:50051"
    restart: on-failure
    networks:
      - network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc_nvidia_app
    command: /bin/bash -c "cd build && ./gRPCNvidia"
    restart: on-failure
    networks:
      - network

networks:
  network:
    driver: bridge
