services:
  nginx:
    image: nginx:latest
    container_name: grpc_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      app:
        condition: service_healthy
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc_nvidia_app
    ports:
      - "50051:50051"
    command: /bin/bash -c "cd build && ./gRPCNvidia"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50051"]
      interval: 10s
      timeout: 5s
      retries: 5
