services:
  nginx:
    image: nginx:latest
    container_name: grpc_server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc_nvidia_app
    ports:
      - "50051:50051"
    command: /bin/bash -c "cd build && ./gRPCNvidia"
    restart: on-failure
