services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc_nvidia_app
    ports:
      - "50051:50051"
    command: /bin/bash -c "cd build && ./gRPCNvidia"
    restart: on-failure
  
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: grpc_nvidia_test
    command: /bin/bash -c "cd build && ctest"
